name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./server/config.ini:/config.ini:ro
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - CLI_BET_NAME=Santiago Lionel
      - CLI_BET_SURNAME=Lorca
      - CLI_BET_DNI=30904465
      - CLI_BET_BIRTH=1999-03-17
      - CLI_BET_NUMBER=2201
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=DEBUG
      - CLI_BET_NAME=Lautaro Valentin
      - CLI_BET_SURNAME=Fornerón
      - CLI_BET_DNI=23772524
      - CLI_BET_BIRTH=1980-02-10
      - CLI_BET_NUMBER=9955
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - CLI_LOG_LEVEL=DEBUG
      - CLI_BET_NAME=Emanuel
      - CLI_BET_SURNAME=Soto
      - CLI_BET_DNI=22069151
      - CLI_BET_BIRTH=2004-03-30
      - CLI_BET_NUMBER=2979
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - CLI_LOG_LEVEL=DEBUG
      - CLI_BET_NAME=Nicolas Andres
      - CLI_BET_SURNAME=Huarte
      - CLI_BET_DNI=29369913
      - CLI_BET_BIRTH=1989-12-05
      - CLI_BET_NUMBER=6857
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - CLI_LOG_LEVEL=DEBUG
      - CLI_BET_NAME=Valentina
      - CLI_BET_SURNAME=Vera
      - CLI_BET_DNI=30170921
      - CLI_BET_BIRTH=1982-05-22	
      - CLI_BET_NUMBER=6053
    volumes:
      - ./client/config.yaml:/config.yaml:ro
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
