package common

const BYTES_SIZE_MESSAGE_TYPE = 4
const BYTES_SIZE_PAYLAOD_SIZE = 4
const BET_FIELDS_NUMBER = 5
const DATA_DELIMITER = "|"

const (
	MESSAGE_TYPE_BET         string = "BET"
	MESSAGE_TYPE_BETS_BATCH  string = "NBET"
	MESSAGE_TYPE_CONNECTION  string = "CONN"
	MESSAGE_TYPE_END_BETS    string = "END"
	MESSAGE_TYPE_GET_WINNERS string = "GWIN"

	MESSAGE_TYPE_OK_RESPONSE      string = "OK"
	MESSAGE_TYPE_NO_OK_RESPONSE   string = "NOK"
	MESSAGE_TYPE_NO_END_RESPONSE  string = "NEND"
	MESSAGE_TYPE_WINNERS_RESPONSE string = "RWIN"
)
