from enum import Enum

BYTES_SIZE_MESSAGE_TYPE = 4
BYTES_SIZE_PAYLAOD_SIZE = 4
BET_FIELDS_NUMBER = 5
MESSAGE_DELIMITER = "|"

class MessageTypes(Enum):
    BET = "BET"
    CONNECTION = "CONN"
    
    OK_RESPONSE = "OK"